# Generated by Django 2.0.13 on 2020-06-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='manhour_jobOfficerName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='manhour_jobTypeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='manhour_otherShopName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='manhour_receiverName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='manhour_senderName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='manhour_shiftName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='manhour_supvrName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='New_manhour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=100, null=True)),
                ('manhour_date', models.DateTimeField(blank=True, null=True)),
                ('manhour_jobNo', models.CharField(blank=True, max_length=100, null=True)),
                ('manhour_fitter', models.CharField(blank=True, max_length=100, null=True)),
                ('manhour_welder', models.CharField(blank=True, max_length=100, null=True)),
                ('manhour_gasCutter', models.CharField(blank=True, max_length=100, null=True)),
                ('manhour_grinder', models.CharField(blank=True, max_length=100, null=True)),
                ('manhour_machineMan', models.CharField(blank=True, max_length=100, null=True)),
                ('manhour_cNc', models.CharField(blank=True, max_length=100, null=True)),
                ('manhour_jobOfficer', models.ManyToManyField(to='manhour.manhour_jobOfficerName')),
                ('manhour_jobType', models.ManyToManyField(to='manhour.manhour_jobTypeName')),
                ('manhour_otherShop', models.ManyToManyField(to='manhour.manhour_otherShopName')),
                ('manhour_receiver', models.ManyToManyField(to='manhour.manhour_receiverName')),
                ('manhour_sender', models.ManyToManyField(to='manhour.manhour_senderName')),
                ('manhour_shift', models.ManyToManyField(to='manhour.manhour_shiftName')),
                ('manhour_supvr', models.ManyToManyField(to='manhour.manhour_supvrName')),
            ],
        ),
    ]
