# Generated by Django 2.0.13 on 2020-06-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='manhour_jobNoName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='new_manhour',
            name='manhour_jobNo',
        ),
        migrations.AddField(
            model_name='new_manhour',
            name='manhour_jobNo',
            field=models.ManyToManyField(to='manhour.manhour_jobNoName'),
        ),
    ]
