# Generated by Django 2.0.13 on 2020-06-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhour', '0004_auto_20200613_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_manhour',
            name='manhour_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
