# Generated by Django 2.0.13 on 2020-06-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhour', '0006_auto_20200613_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManpowerType_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='New_attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=100, null=True)),
                ('attendance_date', models.DateTimeField(blank=True, null=True)),
                ('manpower_attendance', models.CharField(blank=True, max_length=100, null=True)),
                ('manpower_absence', models.CharField(blank=True, max_length=100, null=True)),
                ('attendance_receiver', models.ManyToManyField(to='manhour.manhour_receiverName')),
                ('attendance_sender', models.ManyToManyField(to='manhour.manhour_senderName')),
                ('job_type', models.ManyToManyField(to='manhour.JobType_name')),
                ('manpower_type', models.ManyToManyField(to='manhour.ManpowerType_name')),
            ],
        ),
    ]
