# Generated by Django 2.0.13 on 2020-06-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('job_no', models.CharField(blank=True, max_length=100, null=True)),
                ('received_shop', models.CharField(blank=True, max_length=100, null=True)),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_quantity', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('item_location', models.CharField(blank=True, max_length=100, null=True)),
                ('buy_underJob', models.CharField(blank=True, max_length=100, null=True)),
                ('buy_onDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
