# Generated by Django 2.0.13 on 2020-06-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0003_mrrissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_des', models.CharField(blank=True, max_length=100, null=True)),
                ('material_location', models.CharField(blank=True, max_length=100, null=True)),
                ('material_part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('store_code', models.CharField(blank=True, max_length=100, null=True)),
                ('material_qty', models.CharField(blank=True, max_length=100, null=True)),
                ('material_unit', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
