# Generated by Django 2.0.13 on 2020-06-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0004_materiallist'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiallist',
            name='mrr_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
