# Generated by Django 2.0.13 on 2020-06-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0006_auto_20200622_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstore',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productstore',
            name='min_balance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
