# Generated by Django 2.0.13 on 2020-06-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0007_auto_20200622_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstore',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
