# Generated by Django 2.0.13 on 2020-06-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0011_auto_20200625_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcodename',
            name='item_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/store/name_and_c/'),
        ),
        migrations.AddField(
            model_name='productcodename',
            name='item_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productcodename',
            name='min_balance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
