# Generated by Django 2.0.13 on 2020-06-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0013_productstore_ref_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinCardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('job_no', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_qty', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_qty', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
