# Generated by Django 2.0.13 on 2020-06-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0014_bincardinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bincardinfo',
            name='item_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bincardinfo',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
