# Generated by Django 2.0.13 on 2020-06-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0015_auto_20200627_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='productissue',
            name='qty_after_issue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productissue',
            name='qty_befr_issue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
