# Generated by Django 2.0.13 on 2020-06-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0016_auto_20200627_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrrissue',
            name='mrr_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productissue',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productstore',
            name='buy_onDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
