# Generated by Django 2.0.13 on 2020-06-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0017_auto_20200627_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='bincardinfo',
            name='min_balance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
