# Generated by Django 2.0.13 on 2020-07-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0018_bincardinfo_min_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to', models.CharField(blank=True, max_length=100, null=True)),
                ('quality_no', models.CharField(blank=True, max_length=100, null=True)),
                ('quality_date', models.DateField(blank=True, null=True)),
                ('po_no', models.CharField(blank=True, max_length=100, null=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('memo_no', models.CharField(blank=True, max_length=100, null=True)),
                ('memo_date', models.DateField(blank=True, null=True)),
                ('sign_oic_store', models.ImageField(blank=True, null=True, upload_to='images/store/quality_sign/')),
                ('responsible_oic', models.CharField(blank=True, max_length=100, null=True)),
                ('responsible_oic_date', models.DateField(blank=True, null=True)),
                ('oic_store_sign', models.CharField(blank=True, max_length=100, null=True)),
                ('oic_store_date', models.DateField(blank=True, null=True)),
                ('dgm_sign', models.CharField(blank=True, max_length=100, null=True)),
                ('dgm_date', models.DateField(blank=True, null=True)),
                ('gm_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QualitySign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.ImageField(blank=True, null=True, upload_to='images/store/quality_sign/')),
            ],
        ),
        migrations.AddField(
            model_name='materialquality',
            name='gm_sign',
            field=models.ManyToManyField(to='main_store.QualitySign'),
        ),
    ]
