# Generated by Django 2.0.13 on 2020-08-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0020_auto_20200708_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoNameCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_code', models.CharField(blank=True, max_length=100, null=True)),
                ('p_name', models.CharField(blank=True, max_length=100, null=True)),
                ('p_unit', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
