# Generated by Django 2.0.13 on 2020-08-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0021_demonamecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='demonamecode',
            name='item_under_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productcodename',
            name='item_under_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
