# Generated by Django 2.0.13 on 2020-08-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0023_productissue_item_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productissue',
            name='issuer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
