# Generated by Django 2.0.13 on 2020-09-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0026_qualityitemlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityitemlist',
            name='material_part_no',
        ),
    ]
