# Generated by Django 2.0.13 on 2020-09-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0027_remove_qualityitemlist_material_part_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bincardinfo',
            name='item_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
