# Generated by Django 2.0.13 on 2020-09-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0028_bincardinfo_item_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productissue',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productstore',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
