# Generated by Django 2.0.13 on 2020-09-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0029_auto_20200913_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(blank=True, max_length=100, null=True)),
                ('job_name', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
