# Generated by Django 2.0.13 on 2020-09-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0030_jobnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstore',
            name='item_under_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
