# Generated by Django 2.0.13 on 2020-09-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0032_demojobnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_shop', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_shop', models.CharField(blank=True, max_length=100, null=True)),
                ('indent_date', models.DateField(blank=True, null=True)),
                ('job_no', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(blank=True, max_length=100, null=True)),
                ('indent_no', models.CharField(blank=True, max_length=100, null=True)),
                ('indent_officer', models.CharField(blank=True, max_length=100, null=True)),
                ('sign_indent_offcr', models.ImageField(blank=True, null=True, upload_to='images/main_store/')),
                ('oic_store', models.CharField(blank=True, max_length=100, null=True)),
                ('sign_oic_store', models.ImageField(blank=True, null=True, upload_to='images/main_store/')),
            ],
        ),
        migrations.CreateModel(
            name='IndentMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(blank=True, max_length=200, null=True)),
                ('item_code', models.CharField(blank=True, max_length=50, null=True)),
                ('item_requirement', models.CharField(blank=True, max_length=50, null=True)),
                ('item_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('current_balance', models.CharField(blank=True, max_length=50, null=True)),
                ('prev_buy', models.CharField(blank=True, max_length=50, null=True)),
                ('expect_time', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
