# Generated by Django 2.0.13 on 2020-09-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0033_indent_indentmaterials'),
    ]

    operations = [
        migrations.AddField(
            model_name='indent',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mrrissue',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
