# Generated by Django 2.0.13 on 2020-06-04 15:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='new_iden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100)),
                ('iden_date', models.DateTimeField()),
                ('subject', models.CharField(max_length=300)),
                ('job_no', models.CharField(blank=True, max_length=100, null=True)),
                ('iden_body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_designation', models.CharField(max_length=100)),
                ('sign', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('viewed', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('attention', models.ManyToManyField(blank=True, null=True, to='iden.attention')),
            ],
        ),
        migrations.CreateModel(
            name='receiver_shopName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sender_shopName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='new_iden',
            name='receiver_shop',
            field=models.ManyToManyField(to='iden.receiver_shopName'),
        ),
        migrations.AddField(
            model_name='new_iden',
            name='sender_shop',
            field=models.ManyToManyField(to='iden.sender_shopName'),
        ),
    ]
