# Generated by Django 2.0.13 on 2020-06-11 16:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iden_preview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=100, null=True)),
                ('iden_date', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=300, null=True)),
                ('job_no', models.CharField(blank=True, max_length=100, null=True)),
                ('iden_body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('sign', models.ImageField(blank=True, null=True, upload_to='prevImg/')),
                ('viewed', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='prevDoc/')),
                ('attention', models.ManyToManyField(blank=True, null=True, to='iden.attention')),
                ('receiver_shop', models.ManyToManyField(to='iden.receiver_shopName')),
                ('sender_shop', models.ManyToManyField(to='iden.sender_shopName')),
            ],
        ),
        migrations.AlterField(
            model_name='new_iden',
            name='iden_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new_iden',
            name='ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='new_iden',
            name='sender_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='new_iden',
            name='sender_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='new_iden',
            name='subject',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
